"""empty message

Revision ID: 50faa8a9a170
Revises: 2e68c815a08c
Create Date: 2023-05-18 00:38:26.619260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50faa8a9a170'
down_revision = '2e68c815a08c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('climate', sa.String(length=250), nullable=False),
    sa.Column('diameter', sa.Integer(), nullable=False),
    sa.Column('films', sa.String(length=250), nullable=False),
    sa.Column('gravity', sa.Integer(), nullable=False),
    sa.Column('orbital_period', sa.Integer(), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('residents', sa.String(length=250), nullable=False),
    sa.Column('roation_period', sa.Integer(), nullable=False),
    sa.Column('surface_water', sa.Integer(), nullable=False),
    sa.Column('terrain', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=250), nullable=False),
    sa.Column('element_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('birth_year', sa.String(length=250), nullable=False),
    sa.Column('hair_color', sa.String(length=250), nullable=False),
    sa.Column('films', sa.String(length=250), nullable=False),
    sa.Column('eye_color', sa.String(length=250), nullable=False),
    sa.Column('gender', sa.String(length=250), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('homeworld', sa.Integer(), nullable=True),
    sa.Column('mass', sa.Integer(), nullable=False),
    sa.Column('skin_color', sa.String(length=250), nullable=False),
    sa.Column('starships', sa.String(length=250), nullable=True),
    sa.Column('vehicles', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['homeworld'], ['planets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('people')
    op.drop_table('favorites')
    op.drop_table('planets')
    # ### end Alembic commands ###
